### ISSUE TITLE
CSV parsing error

### ISSUE THREAD

**Issue by rogerdahl** [PASTAplus/dex#79]
A CSV parsing error is not properly propagated to the user, and breaks functionality in DeX.

Example CSV which triggers this: https://dex.edirepository.org/dex/profile/49460

For this CSV, the Profile incorrectly states that the `Temp_QP` and other columns have 100% missing values, and the Subset page returns an error `DataTables warning: table id=csv-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7`.

Note that the CSV passes `csvlint` and opens without issue in LibreOffice.

Exception:
```
2024-09-05 11:04:53 17628    ERROR Exception
Traceback (most recent call last):
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/dex/dex/views/profile.py", line 25, in profile
    csv_df, raw_df, eml_ctx = dex.csv_parser.get_parsed_csv_with_context(rid)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/dex/dex/csv_parser.py", line 29, in get_parsed_csv_with_context
    csv_df = get_parsed_csv(rid, eml_ctx)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/dex/dex/cache.py", line 124, in wrapper
    obj = fn(rid, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/dex/dex/csv_parser.py", line 158, in get_parsed_csv
    return _get_csv(rid, eml_ctx, do_parse=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/dex/dex/csv_parser.py", line 283, in _get_csv
    csv_df = pd.read_csv(**arg_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/pandas/io/parsers/python_parser.py", line 252, in read
    content = self._get_lines(rows)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pasta/miniconda3/envs/dex/lib/python3.11/site-packages/pandas/io/parsers/python_parser.py", line 1127, in _get_lines
    new_row = next(self.data)
              ^^^^^^^^^^^^^^^
_csv.Error: ',' expected after '"'
```

**Comment by rogerdahl** [comment]
Let Miguel Leon know when this has been resolved.

**Comment by rogerdahl** [comment]
The core issue is malformed EML.

The exception that occurs in production is already fixed in the development version.
